### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [openscad/openscad#2529]
After boostorg/logic@23cd89d4c80f build fails. See [error log](https://ptpb.pw/aK-J).

```c++
src/CSGTreeEvaluator.cc:179:9: error: no viable conversion from 'boost::tribool' to 'bool'
                        bool convex = ps->convexValue();
                             ^        ~~~~~~~~~~~~~~~~~
```

**Comment by jbeich** [comment]
Reverting 318585b10672 (only in CSGTreeEvaluator.cc) appears to help. CC @kintel

**Comment by t-paul** [comment]
So shouldn't that be a ticket in Boost as compatibility issue? Or is there some reasonable forward option?

**Comment by jbeich** [comment]
Maybe switch to
```c++
boost::tribool convex = ps->convexValue();
```
or
```c++
bool convex{ps->convexValue()};
```

**Comment by t-paul** [comment]
What's the best way to test such stuff with unreleased boost versions? Are there packages of nightly builds or something similar?

**Comment by jbeich** [comment]
See [develop snapshots](https://dl.bintray.com/boostorg/develop/). Sometimes it's also possible to get away with just headers e.g.,
```
$ git clone https://github.com/boostorg/logic
$ export CXXFLAGS="$CXXFLAGS -I/path/to/logic/include"
$ cmake .
$ make
```
Disclaimer: I'm not a boost developer just a packager, have never tried to build boost outside of downstream build system and don't use openscad myself.

**Comment by kintel** [comment]
@jbeich We cannot assign to a tribool here since we need to test an actual boolean value
If your second suggestion works, that's perfect.

FYI: This may be due to `BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS`: See here for a failing test case: https://github.com/boostorg/logic/commit/82a233bee19691db0046378a390df473e0ea9593#diff-0f78196b9b0d3cb6cb11ba6edeb43e68

Perhaps check if that flag is being set?

**Comment by jbeich** [comment]
> If your second suggestion works, that's perfect.

It does. Actually, I've got the idea from the opposite conversion in
https://github.com/openscad/openscad/blob/8912e648df2f84b42d7406f5d2a50218f72f8ab6/src/GeometryEvaluator.cc#L689

> Perhaps check if `BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS` is being set?

Is there any point? GCC >= 6 and Clang >= 6 default to C++14 and I see `-std=c++11` in my build log.

**Comment by kintel** [comment]
Yeah,  I guess we can use the proper c++11 flag now

**Comment by jbeich** [comment]
> Sounds good! Would you mind opening a Pull Request for that fix?

That maybe hard. `master` requires Qt5QScintilla which (unlike Qt4 one) isn't packaged on FreeBSD. Commenting out 
https://github.com/openscad/openscad/blob/8912e648df2f84b42d7406f5d2a50218f72f8ab6/CMakeLists.txt#L131-L134
leads to an unrelated bustage ([fixed downstream](https://github.com/freebsd/freebsd-ports/blob/1548b5448a3fa91810be061182d28c3cd070d772/cad/openscad-devel/files/patch-src-ModuleCache.h))
```c++
In file included from src/ModuleCache.cc:1:
src/ModuleCache.h:14:2: error: unknown type name 'time_t'
        time_t evaluate(const std::string &filename, class FileModule *&module);
        ^
src/ModuleCache.h:30:3: error: unknown type name 'time_t'
                time_t mtime{};          // time file last modified
                ^
src/ModuleCache.h:31:3: error: unknown type name 'time_t'
                time_t includes_mtime{}; // time the includes last changed
                ^
In file included from src/ModuleCache.cc:1:
In file included from src/ModuleCache.h:4:
In file included from /usr/include/c++/v1/unordered_map:369:
/usr/include/c++/v1/__hash_table:2038:29: error: cannot initialize object parameter of type 'std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *> *>' with an expression of type 'std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *>'
            __pn->__next_ = __h.get()->__ptr();
                            ^~~~~~~~~
/usr/include/c++/v1/unordered_map:1386:21: note: in instantiation of function template specialization 'std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, std::__1::__unordered_map_hasher<std::__1::basic_string<char>, std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, std::__1::hash<std::__1::basic_string<char> >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char>, std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, std::__1::equal_to<std::__1::basic_string<char> >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry> > >::__emplace_unique_key_args<std::__1::basic_string<char>, const std::__1::piecewise_construct_t &, std::__1::tuple<const std::__1::basic_string<char> &>, std::__1::tuple<> >' requested here
    return __table_.__emplace_unique_key_args(__k,
                    ^
src/ModuleCache.cc:53:41: note: in instantiation of member function 'std::__1::unordered_map<std::__1::basic_string<char>, ModuleCache::cache_entry, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, ModuleCache::cache_entry> > >::operator[]' requested here
        cache_entry &cacheEntry = this->entries[filename];
                                               ^
In file included from src/ModuleCache.cc:1:
In file included from src/ModuleCache.h:4:
In file included from /usr/include/c++/v1/unordered_map:369:
/usr/include/c++/v1/__hash_table:2043:23: error: cannot initialize object parameter of type 'std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *> *>' with an expression of type 'std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *>'
                    = __h.get()->__ptr();
                      ^~~~~~~~~
/usr/include/c++/v1/__hash_table:2050:16: error: static_cast from 'std::__1::unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *>, std::__1::__hash_node_destructor<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *> > > >::pointer' (aka 'std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *> *') to 'std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, std::__1::__unordered_map_hasher<std::__1::basic_string<char>, std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, std::__1::hash<std::__1::basic_string<char> >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char>, std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, std::__1::equal_to<std::__1::basic_string<char> >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry> > >::__next_pointer' (aka 'std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char>, ModuleCache::cache_entry>, void *> *> *'), which are not related by inheritance, is not allowed
        __nd = static_cast<__next_pointer>(__h.release());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 errors generated.
```

**Comment by t-paul** [comment]
Are you using the `cmake` build for the application? Right now the main build project is still `qmake` based.

**Comment by jbeich** [comment]
@t-paul, thanks but I've already noticed after looking at downstream package. `cmake -DHEADLESS=OFF` looks broken:
- `find_library(QT5QSCINTILLA_LIBRARY)` missing `PATH_SUFFIXES` unlike `find_path(QT5QSCINTILLA_INCLUDE)`
- `find_package(Qt5)` missing `Multimedia` and `target_link_libraries(OpenSCAD Qt5::Multimedia)`
- No `install` target

**Comment by kintel** [comment]
@jbeich Feel free to open separate issues on cmake topics. The cmake build system hasn't been properly brought up to speed and needs some love.

**Comment by t-paul** [comment]
I'll copy the comment over to #2518.

**Comment by t-paul** [comment]
Added ComboBox fix for Qt4 (works for me), disabled DBus for Qt4 (I don't think it's worth the effort trying to fix that).
