### ISSUE TITLE
Compiling with Qt4

### ISSUE THREAD

**Issue by gskillas** [openscad/openscad#2718]
Hello,

when trying to compile with Qt4 under openSUSE Leap 15.0 I am getting compilation errors while compiling `src/Preferences.cc`

```src/OctoPrint.h: In member function ‘const std::vector<std::pair<const QString, const QString> > OctoPrint::getProfiles(QString) const’:
src/OctoPrint.h:42:87: warning: unused parameter ‘slicer’ [-Wunused-parameter]
  const std::vector<std::pair<const QString, const QString>> getProfiles(const QString slicer) const { return {}; }
                                                                                       ^~~~~~
src/Preferences.cc: In member function ‘void Preferences::on_pushButtonOctoPrintCheckConnection_clicked()’:
src/Preferences.cc:690:17: error: ISO C++ forbids declaration of ‘NetworkException’ with no type [-fpermissive]
  } catch (const NetworkException& e) {
```

Looking at `src/mainwin.cc` I notice that OctoPrint.h is only included for Qt5. This distinction is missing in `src/Preferences.cc`

**Comment by gskillas** [comment]
> Isn't Leap 15 is just released a year ago or so? So why compile with Qt4?
> 
> That said, I'll fix that, we do want to support Qt4 till the next OpenSCAD release is out. After that Qt4 support is going to be removed.

Thank you very much, I would like to move to Qt5 but see #2719 . Exactly same environment, compiling with Qt4 work(ed) while Qt5 fails.

**Comment by gskillas** [comment]
Thanks a lot. It works now with Qt4
