### PR TITLE
Mxe gcc7

### PR DESCRIPTION
**Pull request by t-paul**
- Importing pull request #2447 by @tonytheodore
- Updating build script to use gcc7 plugin

### CODE REVIEW

**Comment by tonytheodore** [comment]
Are you still looking at qt4 support and/or shared builds? I'm making some minor changes to `qmake` so a plain invocation (without any env vars or CONFIG options) will work.

I doubt the openscad shared build would have worked smoothly since the mxe opencsg package has never had shared builds enabled. It's also hard to keep up with packaging shared qt5 as every release introduces new platform plugins etc.

**Comment by t-paul** [comment]
No, while it should still work to build OpenSCAD with Qt4, all the official builds now moved to Qt5 and there's no safeguard in place to keep Qt4 working.

I'm not sure I ever tried the shared build, maybe that was needed earlier? @donbright might have more information on that. I don't think we used that for any of the distributed builds in the last years.

**Comment by donbright** [comment]
@tonytheodore @t-paul  i also vote to abandon qt4 

the shared library build can be abandoned. i was very close to removing it recently. i had some kludges for opencsg and it all worked but ... if i remember correctly, the shared library build was a wild goose chase trying to figure out the source of a bug ... which is no longer necessary to chase down. 

more and more the world is moving away from shared libraries (Rust, Go) so i was actually close to just deleting that whole shared library piece of the build scripts.

**Comment by donbright** [comment]
so this branch seems to be a crash course with my branch msiwinbuild (which builds .msi packages which will be more important as time goes on) however i think i can resolve these conflicts because my branch is going along some of the same lines, use more pkg-config and eliminate a lot of old stuff....

**Comment by t-paul** [comment]
Also #2367, I guess.

**Comment by donbright** [comment]
#2367 is very nice...  if it was possible to combine... we could end up with less lines of code that do more stuff. ...

**Comment by t-paul** [comment]
Yeah, I'm getting a couple of conflicts with #2367. So what about I'll merge #2367 here first and once that makes Travis happy, I'll push it to master. @donbright, you ok with that?

**Comment by t-paul** [comment]
Found qscintilla link issue on MXE, looks like we can use the upstream qscintilla2.prf for MXE builds. Build still running...

**Comment by t-paul** [comment]
Hmm...
```
/opt/mxe/usr/i686-w64-mingw32.static.posix/lib/libmpfr.a(clear.o): In function `mpfr_clear':
/opt/mxe/tmp-mpfr-i686-w64-mingw32.static.posix/mpfr-3.1.5/src/clear.c:28: undefined reference to `__gmp_get_memory_functions'
/opt/mxe/usr/i686-w64-mingw32.static.posix/lib/libmpfr.a(round_prec.o): In function `mpfr_prec_round':
/opt/mxe/tmp-mpfr-i686-w64-mingw32.static.posix/mpfr-3.1.5/src/round_prec.c:72: undefined reference to `__gmp_get_memory_functions'
/opt/mxe/usr/i686-w64-mingw32.static.posix/lib/libmpfr.a(init2.o): In function `mpfr_init2':
/opt/mxe/tmp-mpfr-i686-w64-mingw32.static.posix/mpfr-3.1.5/src/init2.c:55: undefined reference to `__gmp_get_memory_functions'
/opt/mxe/usr/i686-w64-mingw32.static.posix/lib/libmpfr.a(div.o): In function `mpfr_div':
/opt/mxe/tmp-mpfr-i686-w64-mingw32.static.posix/mpfr-3.1.5/src/div.c:434: undefined reference to `__gmpn_divrem'
/opt/mxe/usr/i686-w64-mingw32.static.posix/lib/libmpfr.a(mulders.o): In function `mpfr_divhigh_n':
/opt/mxe/tmp-mpfr-i686-w64-mingw32.static.posix/mpfr-3.1.5/src/mulders.c:319: undefined reference to `__gmpn_divrem'
/opt/mxe/tmp-mpfr-i686-w64-mingw32.static.posix/mpfr-3.1.5/src/mulders.c:326: undefined reference to `__gmpn_divrem'
```

**Comment by tonytheodore** [comment]
Looks like changes to [`cgal.pri`](https://github.com/openscad/openscad/pull/2452/commits/a806fdfdd59f89bf120c7b2ecb8b61fca540f495) weren't transferred to [`cgal.prf`](https://github.com/openscad/openscad/pull/2452/commits/eb79597f236dfaf86de2249c22c1c4bdb46b27f2#diff-44f277e9b2e2c0a55542ceb859e173ca).

**Comment by t-paul** [comment]
Ugh, I may have merged the wrong way around when resolving the conflicts. Thanks for the pointer, I'll check tomorrow.

**Comment by t-paul** [comment]
MXE builds based on gcc7 are good now, including AMF and ZIP (thanks to @nophead for #2471). New [snapshots](http://www.openscad.org/downloads.html#snapshots) are up.

**Comment by nophead** [comment]
Thanks for the snapshot.

**Comment by MichaelAtOz** [comment]
Works.

```
OpenSCAD Version: 2018.09.05 (git 40af343)
System information: Windows(TM) 6.1 SP 1.0 NTW 1 MSDN 724833 2 CPUs 3.94 GB RAM
Compiler: GCC "7.3.0" 64bit
Boost version: 1_60
Eigen version: 3.2.5
CGAL version, kernels: 4.11, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.11.1
QScintilla version: 2.10.4
MingW build: MingW64
GLib version: 2.50.2
libzip version: 1.5.1
Application Path: C:/Program Files/openscad-2018.09.05
Documents Path: C:\Users\Testing\Documents
Resource Path: C:/Program Files/openscad-2018.09.05
User Library Path: C:/Users/Testing/Documents/OpenSCAD/libraries
User Config Path: C:\Users\Testing\AppData\Local/OpenSCAD
Backup Path: C:/Users/Testing/Documents/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
C:/Users/Testing/Documents/OpenSCAD/libraries
C:/Program Files/openscad-2018.09.05\libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.12.0
OpenGL Version: 3.3.0
GL Renderer: ION/integrated/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QGLWidgetGL Extensions:
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_blend_func_extended
GL_ARB_clear_buffer_object
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_draw_buffers
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_separate_shader_objects
GL_ARB_shader_bit_encoding
GL_ARB_shader_objects
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback_instanced
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXTX_framebuffer_mixed_formats
GL_EXT_Cg_shader
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_import_sync_object
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_shader_objects
GL_EXT_separate_specular_color
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback2
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_KHR_debug
GL_KTX_buffer_region
GL_NVX_conditional_render
GL_NVX_gpu_memory_info
GL_NV_ES1_1_compatibility
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_depth_clamp
GL_NV_explicit_multisample
GL_NV_fence
GL_NV_float_buffer
GL_NV_fog_distance
GL_NV_fragment_program
GL_NV_fragment_program2
GL_NV_fragment_program_option
GL_NV_framebuffer_multisample_coverage
GL_NV_geometry_shader4
GL_NV_gpu_program4
GL_NV_half_float
GL_NV_light_max_exponent
GL_NV_multisample_coverage
GL_NV_multisample_filter_hint
GL_NV_occlusion_query
GL_NV_packed_depth_stencil
GL_NV_parameter_buffer_object
GL_NV_parameter_buffer_object2
GL_NV_path_rendering
GL_NV_pixel_data_range
GL_NV_point_sprite
GL_NV_primitive_restart
GL_NV_register_combiners
GL_NV_register_combiners2
GL_NV_shader_buffer_load
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_compression_vtc
GL_NV_texture_env_combine4
GL_NV_texture_expand_normal
GL_NV_texture_multisample
GL_NV_texture_rectangle
GL_NV_texture_shader
GL_NV_texture_shader2
GL_NV_texture_shader3
GL_NV_transform_feedback
GL_NV_transform_feedback2
GL_NV_vertex_array_range
GL_NV_vertex_array_range2
GL_NV_vertex_buffer_unified_memory
GL_NV_vertex_program
GL_NV_vertex_program1_1
GL_NV_vertex_program2
GL_NV_vertex_program2_option
GL_NV_vertex_program3
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_lod
GL_SGIX_depth_texture
GL_SGIX_shadow
GL_SUN_slice_accum
GL_WIN_swap_hint
WGL_EXT_swap_control
```

**Comment by t-paul** [comment]
Thanks @MichaelAtOz.

Older Debian based distros did not build on OBS as `qmake` did not find the *.prf files in the new sub-folder. I'm not sure if that is an OBS thing yet, adding
```
export QMAKEFEATURES=$(CURDIR)/features
```
to the `debian.rules` file fixes that. With that all builds I know of are back to green.
