### ISSUE TITLE
Build failure - latest cgalutils-tess.cc fails to compile on Ubuntu 20.04.6

### ISSUE THREAD

**Issue by smartavionics** [openscad/openscad#5988]
**Describe the bug**
Building the current source, I am now seeing a compilation failure.

**To Reproduce**
Check out latest source and build

**Expected behavior**
Compilation succeeds.

**Code reproducing the issue**

**Screenshots**
```
~/3dp/openscad.git/build[master]$ make -k
[  0%] Automatic MOC and UIC for target OpenSCAD
[  2%] Built target OpenSCAD_autogen
[  6%] Built target mimalloc-static
[  7%] Built target Clipper2
[ 13%] Built target manifold
[ 13%] Building CXX object CMakeFiles/OpenSCAD.dir/src/geometry/cgal/cgalutils-tess.cc.o
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:11:71: error: ‘K’ was not declared in this scope
   11 | using Projection = CGAL::Triangulation_2_filtered_projection_traits_3<K>;
      |                                                                       ^
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:11:72: error: template argument 1 is invalid
   11 | using Projection = CGAL::Triangulation_2_filtered_projection_traits_3<K>;
      |                                                                        ^
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:25:65: error: ‘Tess_kernel’ was not declared in this scope
   25 | using Fbb = CGAL::Triangulation_face_base_with_info_2<FaceInfo, Tess_kernel>;
      |                                                                 ^~~~~~~~~~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:25:76: error: template argument 2 is invalid
   25 | using Fbb = CGAL::Triangulation_face_base_with_info_2<FaceInfo, Tess_kernel>;
      |                                                                            ^
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:25:76: error: template argument 3 is invalid
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:84: error: ‘Projection’ was not declared in this scope
   26 | using Tds = CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<Projection>, CGAL::Constrained_triangulation_face_base_2<Projection, Fbb>>;
      |                                                                                    ^~~~~~~~~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:94: error: template argument 1 is invalid
   26 | using Tds = CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<Projection>, CGAL::Constrained_triangulation_face_base_2<Projection, Fbb>>;
      |                                                                                              ^
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:141: error: ‘Projection’ was not declared in this scope
   26 | g Tds = CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<Projection>, CGAL::Constrained_triangulation_face_base_2<Projection, Fbb>>;
      |                                                                                                                                         ^~~~~~~~~~

/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:153: error: ‘Fbb’ was not declared in this scope
   26 | ::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<Projection>, CGAL::Constrained_triangulation_face_base_2<Projection, Fbb>>;
      |                                                                                                                                         ^~~

/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:153: error: template argument 1 is invalid
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:153: error: template argument 2 is invalid
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:156: error: template argument 1 is invalid
   26 | riangulation_data_structure_2<CGAL::Triangulation_vertex_base_2<Projection>, CGAL::Constrained_triangulation_face_base_2<Projection, Fbb>>;
      |                                                                                                                                         ^~

/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:26:156: error: template argument 2 is invalid
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:27:56: error: ‘Projection’ was not declared in this scope
   27 | using CDT = CGAL::Constrained_Delaunay_triangulation_2<Projection, Tds, CGAL::Exact_predicates_tag>;
      |                                                        ^~~~~~~~~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:27:68: error: ‘Tds’ was not declared in this scope
   27 | using CDT = CGAL::Constrained_Delaunay_triangulation_2<Projection, Tds, CGAL::Exact_predicates_tag>;
      |                                                                    ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:27:99: error: template argument 1 is invalid
   27 | using CDT = CGAL::Constrained_Delaunay_triangulation_2<Projection, Tds, CGAL::Exact_predicates_tag>;
      |                                                                                                   ^
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:27:99: error: template argument 2 is invalid
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:30:26: error: variable or field ‘mark_domains’ declared void
   30 | static void mark_domains(CDT& ct,
      |                          ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:30:26: error: ‘CDT’ was not declared in this scope
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:30:31: error: ‘ct’ was not declared in this scope
   30 | static void mark_domains(CDT& ct,
      |                               ^~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:31:26: error: ‘CDT’ has not been declared
   31 |                          CDT::Face_handle start,
      |                          ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:32:26: error: expected primary-expression before ‘int’
   32 |                          int index,
      |                          ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:33:36: error: ‘CDT’ was not declared in this scope
   33 |                          std::list<CDT::Edge>& border)
      |                                    ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:33:45: error: template argument 1 is invalid
   33 |                          std::list<CDT::Edge>& border)
      |                                             ^
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:33:45: error: template argument 2 is invalid
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:33:48: error: ‘border’ was not declared in this scope
   33 |                          std::list<CDT::Edge>& border)
      |                                                ^~~~~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:62:26: error: variable or field ‘mark_domains’ declared void
   62 | static void mark_domains(CDT& cdt)
      |                          ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:62:26: error: ‘CDT’ was not declared in this scope
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:62:31: error: ‘cdt’ was not declared in this scope
   62 | static void mark_domains(CDT& cdt)
      |                               ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc: In function ‘bool CGALUtils::tessellatePolygonWithHoles(const std::vector<std::vector<CGAL::Point_3<CGAL::Epick> > >&, Polygons&, const CGAL::Vector_3<CGAL::Epick>*)’:
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:115:3: error: ‘Projection’ was not declared in this scope; did you mean ‘project’?
  115 |   Projection actualProjection(normalvec);
      |   ^~~~~~~~~~
      |   project
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:116:3: error: ‘CDT’ was not declared in this scope
  116 |   CDT cdt(actualProjection);
      |   ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:119:7: error: ‘cdt’ was not declared in this scope
  119 |       cdt.insert_constraint(poly[i], poly[(i + 1) % poly.size()]);
      |       ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:124:16: error: ‘cdt’ was not declared in this scope
  124 |   mark_domains(cdt);
      |                ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:124:3: error: ‘mark_domains’ was not declared in this scope
  124 |   mark_domains(cdt);
      |   ^~~~~~~~~~~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:127:8: error: ‘CDT’ is not a class, namespace, or enumeration
  127 |   for (CDT::Finite_faces_iterator fit = cdt.finite_faces_begin();
      |        ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:128:8: error: ‘fit’ was not declared in this scope
  128 |        fit != cdt.finite_faces_end(); fit++) {
      |        ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc: In function ‘bool CGALUtils::tessellatePolygon(const std::vector<CGAL::Point_3<CGAL::Epick> >&, Polygons&, const CGAL::Vector_3<CGAL::Epick>*)’:
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:171:3: error: ‘Projection’ was not declared in this scope; did you mean ‘project’?
  171 |   Projection actualProjection(normalvec);
      |   ^~~~~~~~~~
      |   project
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:172:3: error: ‘CDT’ was not declared in this scope
  172 |   CDT cdt(actualProjection);
      |   ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:174:5: error: ‘cdt’ was not declared in this scope
  174 |     cdt.insert_constraint(polygon[i], polygon[(i + 1) % polygon.size()]);
      |     ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:178:16: error: ‘cdt’ was not declared in this scope
  178 |   mark_domains(cdt);
      |                ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:178:3: error: ‘mark_domains’ was not declared in this scope
  178 |   mark_domains(cdt);
      |   ^~~~~~~~~~~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:181:3: error: ‘CDT’ is not a class, namespace, or enumeration
  181 |   CDT::Finite_faces_iterator fit;
      |   ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:182:8: error: ‘fit’ was not declared in this scope
  182 |   for (fit = cdt.finite_faces_begin(); fit != cdt.finite_faces_end(); ++fit) {
      |        ^~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:186:9: error: ‘Tess_kernel’ has not been declared
  186 |         Tess_kernel::Point_3 v = cdt.triangle(fit)[i];
      |         ^~~~~~~~~~~
/home/markb/3dp/openscad.git/src/geometry/cgal/cgalutils-tess.cc:187:32: error: ‘v’ was not declared in this scope
  187 |         tri.push_back(Vector3d(v.x(), v.y(), v.z()));
      |                                ^
make[2]: *** [CMakeFiles/OpenSCAD.dir/build.make:511: CMakeFiles/OpenSCAD.dir/src/geometry/cgal/cgalutils-tess.cc.o] Error 1
[ 14%] Building CXX object CMakeFiles/OpenSCAD.dir/src/geometry/cgal/cgalutils-triangulate.cc.o
[ 14%] Building CXX object CMakeFiles/OpenSCAD.dir/src/geometry/cgal/CGALNefGeometry.cc.o
[ 14%] Building CXX object CMakeFiles/OpenSCAD.dir/src/geometry/cgal/CGALCache.cc.o

```

**Environment and Version info (please complete the following information):**
```
System:    Host: toucan Kernel: 5.15.0-136-generic x86_64 bits: 64 Desktop: Xfce 4.16.1 
           Distro: Ubuntu 20.04.6 LTS (Focal Fossa) 
Machine:   Type: Laptop System: GIGABYTE product: GB-BSi3-6100 v: 1.x serial: <superuser/root required> 
           Mobo: GIGABYTE model: MKLP3AP-00 v: 1.x serial: <superuser/root required> UEFI [Legacy]: American Megatrends v: F5 
           date: 01/29/2016 
CPU:       Topology: Dual Core model: Intel Core i3-6100U bits: 64 type: MT MCP L2 cache: 3072 KiB 
           Speed: 977 MHz min/max: 400/2300 MHz Core speeds (MHz): 1: 977 2: 1535 3: 1089 4: 1593 
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 21.2.6 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio driver: snd_hda_intel 
           Device-2: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo 
           Sound Server: ALSA v: k5.15.0-136-generic 
Network:   Device-1: Intel Ethernet I219-V driver: e1000e 
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: 40:8d:5c:f4:c2:44 
           Device-2: Intel Wireless 3165 driver: iwlwifi 
           IF: wlp1s0 state: down mac: ac:2b:6e:15:50:54 
           Device-3: Lite-On Dell Wireless Device type: USB driver: hid-generic,usbhid 
Drives:    Local Storage: total: 1.82 TiB used: 1.06 TiB (58.3%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 870 EVO 1TB size: 931.51 GiB 
           ID-2: /dev/sdb type: USB vendor: Western Digital model: WD Elements 2621 size: 931.48 GiB 
Partition: ID-1: / size: 915.32 GiB used: 308.37 GiB (33.7%) fs: ext4 dev: /dev/sda5 
Sensors:   System Temperatures: cpu: 60.0 C mobo: 29.8 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 292 Uptime: 64d 14h 22m Memory: 15.49 GiB used: 8.68 GiB (56.0%) Shell: bash inxi: 3.0.38 
```

**Library & Graphics card information**
```
OpenSCAD Version: 2025.05.02
System information: Linux 5.15.0-136-generic #147~20.04.1-Ubuntu SMP Wed Mar 19 16:13:14 UTC 2025 x86_64 Ubuntu 20.04.6 LTS 4 CPUs 15.49 GB RAM
User Agent: OpenSCAD/2025.05.02 (Linux x86_64; Ubuntu 20.04.6 LTS)
Compiler: GCC "9.4.0" 64bit
MinGW build: No
Debug build: No
Boost version: 1_71
Eigen version: 3.3.7
CGAL version, kernels: 5.0.2, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
Python Version: Python 3.8.10
OpenCSG version: OpenCSG 1.4.2
Clipper2 version: 1.5.2
Manifold version: 3.0.1
Qt version: 5.12.8
QScintilla version: 2.11.2
InputDrivers: 
GLib version: 2.64.6
lodepng version: 20230410
libzip version: 1.5.1
fontconfig version: 2.13.1
freetype version: 2.10.1
harfbuzz version: 2.6.4
cairo version: 1.16.0
lib3mf version: 1.8.1
Features: roof, input-driver-dbus, lazy-union, vertex-object-renderers-indexing, textmetrics, import-function, predictible-output, python-engine
Application Path: /usr/local/bin
Documents Path: /home/markb/.local/share
User Documents Path: /home/markb/Documents
Resource Path: /usr/local/share/openscad
User Library Path: /home/markb/.local/share/OpenSCAD/libraries
User Examples Path: /home/markb/.local/share/OpenSCAD/examples
User Config Path: /home/markb/.config/OpenSCAD
Backup Path: /home/markb/.local/share/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
/home/markb/.local/share/OpenSCAD/libraries
/usr/local/share/openscad/libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
/usr/share/fonts
/usr/local/share/fonts
/home/markb/.local/share/fonts
/home/markb/.fonts
/usr/share/texmf/fonts/opentype/public/lm
/usr/share/texmf/fonts/opentype/public/lm-math
/usr/share/texmf/fonts/opentype/public/tex-gyre
/usr/share/texmf/fonts/opentype/public/tex-gyre-math
/usr/X11/lib/X11/fonts
/System/Library/Fonts
/Library/Fonts
/home/markb/Library/Fonts
/usr/share/fonts/X11
/usr/share/fonts/cMap
/usr/share/fonts/cmap
/usr/share/fonts/eot
/usr/share/fonts/opentype
/usr/share/fonts/svg
/usr/share/fonts/truetype
/usr/share/fonts/type1
/usr/share/fonts/woff
/home/markb/.fonts/Library
/home/markb/.fonts/noto
/home/markb/.fonts/r
/usr/share/fonts/X11/Type1
/usr/share/fonts/X11/encodings
/usr/share/fonts/X11/misc
/usr/share/fonts/X11/util
/usr/share/fonts/cmap/adobe-cns1
/usr/share/fonts/cmap/adobe-gb1
/usr/share/fonts/cmap/adobe-japan1
/usr/share/fonts/cmap/adobe-japan2
/usr/share/fonts/cmap/adobe-korea1
/usr/share/fonts/eot/font-awesome
/usr/share/fonts/opentype/font-awesome
/usr/share/fonts/opentype/malayalam
/usr/share/fonts/opentype/mathjax
/usr/share/fonts/opentype/noto
/usr/share/fonts/opentype/urw-base35
/usr/share/fonts/svg/font-awesome
/usr/share/fonts/truetype/Gargi
/usr/share/fonts/truetype/Gubbi
/usr/share/fonts/truetype/Nakula
/usr/share/fonts/truetype/Navilu
/usr/share/fonts/truetype/Sahadeva
/usr/share/fonts/truetype/Sarai
/usr/share/fonts/truetype/abyssinica
/usr/share/fonts/truetype/ancient-scripts
/usr/share/fonts/truetype/baskerville
/usr/share/fonts/truetype/dejavu
/usr/share/fonts/truetype/droid
/usr/share/fonts/truetype/font-awesome
/usr/share/fonts/truetype/fonts-beng-extra
/usr/share/fonts/truetype/fonts-deva-extra
/usr/share/fonts/truetype/fonts-gujr-extra
/usr/share/fonts/truetype/fonts-guru-extra
/usr/share/fonts/truetype/fonts-kalapi
/usr/share/fonts/truetype/fonts-orya-extra
/usr/share/fonts/truetype/fonts-telu-extra
/usr/share/fonts/truetype/fonts-yrsa-rasa
/usr/share/fonts/truetype/freefont
/usr/share/fonts/truetype/kacst
/usr/share/fonts/truetype/kacst-one
/usr/share/fonts/truetype/lao
/usr/share/fonts/truetype/lato
/usr/share/fonts/truetype/liberation
/usr/share/fonts/truetype/liberation2
/usr/share/fonts/truetype/lohit-assamese
/usr/share/fonts/truetype/lohit-bengali
/usr/share/fonts/truetype/lohit-devanagari
/usr/share/fonts/truetype/lohit-gujarati
/usr/share/fonts/truetype/lohit-kannada
/usr/share/fonts/truetype/lohit-malayalam
/usr/share/fonts/truetype/lohit-oriya
/usr/share/fonts/truetype/lohit-punjabi
/usr/share/fonts/truetype/lohit-tamil
/usr/share/fonts/truetype/lohit-tamil-classical
/usr/share/fonts/truetype/lohit-telugu
/usr/share/fonts/truetype/lyx
/usr/share/fonts/truetype/malayalam
/usr/share/fonts/truetype/noto
/usr/share/fonts/truetype/openoffice
/usr/share/fonts/truetype/padauk
/usr/share/fonts/truetype/pagul
/usr/share/fonts/truetype/porson
/usr/share/fonts/truetype/roboto
/usr/share/fonts/truetype/samyak
/usr/share/fonts/truetype/samyak-fonts
/usr/share/fonts/truetype/sinhala
/usr/share/fonts/truetype/tibetan-machine
/usr/share/fonts/truetype/tlwg
/usr/share/fonts/truetype/ttf-bitstream-vera
/usr/share/fonts/truetype/ttf-khmeros-core
/usr/share/fonts/truetype/ubuntu
/usr/share/fonts/truetype/vlgothic
/usr/share/fonts/type1/gsfonts
/usr/share/fonts/type1/texlive-fonts-recommended
/usr/share/fonts/type1/urw-base35
/usr/share/fonts/woff/font-awesome
/usr/share/fonts/X11/encodings/large
/usr/share/fonts/truetype/roboto/hinted
/usr/share/fonts/truetype/roboto/unhinted
/usr/share/fonts/truetype/roboto/unhinted/RobotoTTF
GLEW version: 2.1.0
OpenGL Version: 3.0 Mesa 21.2.6
GL Renderer: Mesa DRI Intel(R) HD Graphics 520 (SKL GT2)
GL Vendor: Intel Open Source Technology Center
RGBA(8880), depth(0), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8880), depth(0), stencil(0)

GL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_conservative_depth
GL_AMD_depth_clamp_separate
GL_AMD_draw_buffers_blend
GL_AMD_multi_draw_indirect
GL_AMD_query_buffer_object
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_stencil_export
GL_AMD_shader_trinary_minmax
GL_AMD_texture_texture4
GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5
GL_APPLE_object_purgeable
GL_APPLE_packed_pixels
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_parallel_shader_compile
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_spirv_extensions
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_draw_buffers
GL_ATI_separate_stencil
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_EXT_EGL_image_storage
GL_EXT_EGL_sync
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_texture
GL_EXT_demote_to_helper_invocation
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_memory_object
GL_EXT_memory_object_fd
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_semaphore
GL_EXT_semaphore_fd
GL_EXT_separate_specular_color
GL_EXT_shader_framebuffer_fetch
GL_EXT_shader_framebuffer_fetch_non_coherent
GL_EXT_shader_integer_mix
GL_EXT_shader_samples_identical
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texture
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shadow_lod
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_IBM_multimode_draw_arrays
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_INGR_blend_func_separate
GL_INTEL_blackhole_render
GL_INTEL_performance_query
GL_INTEL_shader_atomic_float_minmax
GL_INTEL_shader_integer_functions2
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_KHR_texture_compression_astc_ldr
GL_KHR_texture_compression_astc_sliced_3d
GL_MESA_pack_invert
GL_MESA_shader_integer_functions
GL_MESA_texture_signed_rgba
GL_MESA_window_pos
GL_NV_blend_square
GL_NV_compute_shader_derivatives
GL_NV_conditional_render
GL_NV_depth_clamp
GL_NV_fog_distance
GL_NV_fragment_shader_interlock
GL_NV_half_float
GL_NV_light_max_exponent
GL_NV_packed_depth_stencil
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_env_combine4
GL_NV_texture_rectangle
GL_OES_EGL_image
GL_OES_read_format
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays
```
**Additional context**

**Comment by kintel** [comment]
I'm not sure older Ubuntu will keep being able to build OpenSCAD. GitHub recently disabled Ubuntu 20.04 CI runner so we're no longer building it daily.
Some leading questions:
* Are you building from source because you're somehow unable to use our nightly binaries?
* Are you unable to upgrade to a more recent Ubuntu version?
* Is this a recent regression?

You might be on your own, but leaving this open in case someone wants to go digging..

**Comment by smartavionics** [comment]
Thanks for the speedy reply. Answers...

1 - I haven't tried using your nightlies before but I just installed the snap and it appears to run OK so I will move to using that.

2 - Probably could upgrade the Ubuntu but it's not on my agenda right now.

3 - Yes, it's a recent regression.

I can understand not wanting to support builds on old platforms so I don't mind if you don't fix this issue.

Please close when it suits you.

**Comment by t-paul** [comment]
The issue is actually a not updated code path for CGAL < 5.4. Due to Ubuntu 20.04. being out of standard support, it's not covered by any automatic builds and/or tests anymore.

Anyway, should be fixed by the linked commit.
